import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en-US" | "pt-BR" | "es-ES";

const translations = {
  "en-US": {
    "header.subtitle": "Interactive Web Security Learning Platform",
    "header.light": "Light",
    "header.dark": "Dark",
    "sidebar.difficulty": "Security Level",
    "sidebar.modules": "Learning Modules",
    "sidebar.status": "Session Status",
    "sidebar.current": "Module",
    "sidebar.level": "Level",
    "difficulty.easy": "Easy",
    "difficulty.low": "Low",
    "difficulty.medium": "Medium", 
    "difficulty.hard": "Hard",
    "difficulty.high": "High",
    "difficulty.impossible": "Impossible",
    "security.low": "Low",
    "security.medium": "Medium",
    "security.high": "High",
    "security.level": "Security Level",
    "modules.home": "Home",
    "modules.sql-injection": "SQL Injection",
    "modules.sql-blind": "SQL Injection (Blind)",
    "modules.xss": "Cross-Site Scripting",
    "modules.command-injection": "Command Injection",
    "modules.csrf": "CSRF Protection",
    "modules.file-inclusion": "File Inclusion", 
    "modules.auth-bypass": "Auth Bypass",
    "modules.brute-force": "Brute Force",
    "modules.file-upload": "File Upload",
    "modules.insecure-captcha": "Insecure CAPTCHA",
    "modules.weak-session": "Weak Session IDs",
    "modules.coming_soon": "Module coming soon...",
    "modules.learn": "Learn",
    "learn.mode": "Learn Mode",
    "learn.guided": "Guided Learning",
    "learn.fundamentals": "Security Fundamentals",
    "learn.web_security": "Web Security",
    "learn.network_security": "Network Security",
    "learn.os_security": "Operating Systems Security",
    "learn.programming_security": "Secure Programming",
    "home.title": "Welcome to CyberLab",
    "home.subtitle": "Interactive Web Security Learning Platform",
    "home.description": "CyberLab is an interactive educational platform designed to teach and train web security in a controlled and safe environment. The goal of this platform is to empower students, developers, and security professionals to learn, explore, and understand common web application vulnerabilities through hands-on practice.",
    "home.get_started": "Get Started",
    "home.general_instructions": "General Instructions",
    "home.general_instructions_content": "Users can explore the modules in any order, depending on their knowledge level. Each module includes theory, practical examples, and interactive challenges, allowing users to validate their exploitation attempts. The system also contains hidden and undocumented scenarios to encourage curiosity and promote more creative pentesting approaches. A learning mode is available with hints, tutorials, and additional references.",
    "home.warning": "WARNING!",
    "home.warning_content": "CyberLab is a deliberately vulnerable platform, created exclusively for educational purposes. It must NOT be deployed on production servers or exposed to the public internet, as this may compromise the environment's security. It is strongly recommended to run CyberLab in isolated virtual machines or other controlled lab environments.",
    "home.disclaimer": "Disclaimer",
    "home.disclaimer_content": "The developers of CyberLab take no responsibility for any misuse of the platform. This system must be used only for learning purposes and in accordance with ethical and legal practices.",
    "home.features.interactive": "Interactive Learning",
    "home.features.interactive_desc": "Practice with real vulnerabilities",
    "home.features.multilingual": "Multilingual Support",
    "home.features.multilingual_desc": "Available in multiple languages",
    "home.features.difficulty": "Progressive Difficulty",
    "home.features.difficulty_desc": "From beginner to expert levels",
    "sql.title": "SQL Injection",
    "sql.description": "Learn how SQL injection vulnerabilities work and how to exploit them safely.",
    "sql.user_id": "User ID",
    "sql.submit": "Query Database",
    "sql.results": "Query Results",
    "sql.placeholder": "Enter user ID to search...",
    "xss.title": "Cross-Site Scripting (XSS)",
    "xss.description": "Understand XSS vulnerabilities and practice exploiting them.",
    "xss.message": "Message",
    "xss.submit": "Submit Message",
    "xss.results": "Message Display",
    "xss.placeholder": "Enter your message...",
    "command.search": "Search modules...",
    "command.no_results": "No results found.",
    "command.navigation": "Navigation",
    "command.categories": "Learn Categories",
    "command.topics": "Learn Topics",
    
    // Learn Mode
    "learn.category_not_found": "Category Not Found",
    "learn.category_not_found_desc": "The requested learning category does not exist.",
    "learn.progress": "Progress",
    "learn.lessons": "lessons",
    "learn.completed": "completed",
    "learn.lesson_sections": "Lesson Sections",
    "learn.previous_section": "Previous Section",
    "learn.next_section": "Next Section",
    "learn.key_points": "Key Points",
    "learn.code_examples": "Code Examples",
    "learn.vulnerable_code": "Vulnerable Code",
    "learn.secure_code": "Secure Code",
    "learn.vulnerable_implementation": "Vulnerable Implementation",
    "learn.secure_implementation": "Secure Implementation",
    "learn.why_vulnerable": "Why it's vulnerable:",
    "learn.why_secure": "Why it's secure:",
    "learn.prevention_strategies": "Prevention Strategies",
    "learn.theory": "Theory",
    "learn.practical": "Practical",
    "learn.security_fundamentals_desc": "Essential security concepts and principles",
    "learn.web_security_desc": "Web application security practices",
    "learn.network_security_desc": "Network protection and protocols",
    "learn.network_protocols_desc": "Understanding network protocols and security",
    "learn.firewalls_ids_desc": "Firewall configuration and intrusion detection",
    "learn.encryption_pki_desc": "Cryptography and public key infrastructure",
    "learn.understanding": "Understanding",
    "learn.secure_development": "Secure Development",
    "learn.protection_and": "Protection and",
    "learn.complete_lesson": "Complete Lesson",
    
    // 404 Page
    "notfound.title": "Page Not Found",
    "notfound.description": "The page you're looking for doesn't exist or has been moved.",
    "notfound.return_home": "Return to Home",
    
    // SQL Blind Module
    "sql_blind.title": "SQL Injection (Blind)",
    "sql_blind.description": "Learn about blind SQL injection techniques and exploitation methods.",
    "sql_blind.user_id": "User ID",
    "sql_blind.search_user": "Search User",
    "sql_blind.querying": "Querying...",
    "sql_blind.analysis_results": "Analysis Results - Technique:",
    "sql_blind.query": "Query:",
    "sql_blind.response": "Response:",
    "sql_blind.response_time": "Response Time:",
    "sql_blind.suspicious_delay": "Suspicious delay!",
    "sql_blind.analysis_notes": "Analysis Notes",
    "sql_blind.prevention_measures": "Prevention Measures",
    "sql_blind.payloads_title": "Blind SQL Injection Payloads:",
    "sql_blind.boolean_based": "Boolean-based:",
    "sql_blind.time_based_mysql": "Time-based (MySQL):",
    "sql_blind.time_based_sqlserver": "Time-based (SQL Server):",
    "sql_blind.data_extraction": "Data extraction:",
    "sql_blind.boolean_blind_technique": "Boolean-based Blind",
    "sql_blind.time_based_blind_technique": "Time-based Blind", 
    "sql_blind.boolean_limited_technique": "Boolean-based (Limited)",
    "sql_blind.boolean_injection_successful": "Boolean-based blind injection successful!",
    "sql_blind.time_injection_successful": "Time-based blind injection successful!",
    "sql_blind.boolean_vulnerability_confirmed": "This confirms boolean-based blind injection vulnerability",
    "sql_blind.time_techniques_effective": "Time-based techniques may be more effective",
    "sql_blind.boolean_blind_description": " - Boolean-based blind injection",
    "sql_blind.time_blind_description": " - Time-based blind injection",
    "sql_blind.advanced_blind_description": " - Advanced blind techniques",
    "sql_blind.input_validation_implemented": "✓ Input validation implemented",
    "sql_blind.proper_error_handling": "✓ Proper error handling",
    "sql_blind.implement_input_validation": "Implement proper input validation",
    "sql_blind.add_query_timeouts": "Add query timeouts to prevent time-based attacks",
    "sql_blind.implement_error_handling": "Implement proper error handling",
    "sql_blind.try_time_based_payloads": "Try time-based payloads: ' AND SLEEP(5)-- or boolean conditions",
    
    // TOTP/2FA Authentication Module
    "totp.title": "TOTP/2FA Authentication",
    "totp.description": "Learn about Time-Based One-Time Password two-factor authentication implementation",
    "totp.enable_2fa": "Enable Two-Factor Authentication",
    "totp.qr_code_instruction": "Scan this QR code with your authenticator app",
    "totp.secret_key": "Secret key:",
    "totp.enter_code": "Enter the 6-digit code from your authenticator app",
    "totp.verify_code": "Verify Code",
    "totp.login_attempts": "Login Attempts",
    "totp.easy_level": "Easy - The Predictable Token",
    "totp.medium_level": "Medium - The Flawed Validation",
    "totp.hard_level": "Hard - The Cryptographic Leak",
    "totp.exploitation_tips": "Exploitation Tips:",
    "totp.weak_secret": "Weak secret and long time window",
    "totp.no_rate_limiting": "No rate limiting on attempts",
    "totp.secret_exposure": "Secret exposed in responses",
    
    // JWT Authentication Module
    "jwt.title": "JWT Authentication",
    "jwt.description": "Learn about vulnerabilities in JWT implementations",
    "jwt.login_generate": "Login & Generate JWT",
    "jwt.current_token": "Current Token",
    "jwt.decoded_payload": "Decoded Payload",
    "jwt.custom_token_test": "Custom Token Testing",
    "jwt.validate_token": "Validate Token",
    "jwt.public_key_endpoint": "Public Key Endpoint",
    "jwt.jku_configuration": "JKU Header Configuration",
    "jwt.malicious_jku_url": "Malicious JKU URL",
    "jwt.easy_level": "Easy - The None Algorithm",
    "jwt.medium_level": "Medium - Algorithm Confusion",
    "jwt.hard_level": "Hard - JKU Header Injection",
    "jwt.none_algorithm": "Accepts 'none' algorithm",
    "jwt.algorithm_confusion": "Algorithm confusion",
    "jwt.jku_injection": "JKU header injection",
    "jwt.exploitation_steps": "Exploitation Steps:",
    "jwt.load_example": "Load Example Token",
    
    // XSS Module  
    "xss.message_board": "Message Board System",
    "xss.processing": "Processing...",
    "xss.message_preview": "Message Preview:",
    "xss.security_analysis": "Security Analysis",
    "xss.original_input": "Original Input:",
    "xss.processed_output": "Processed Output:",
    "xss.educational_note": "Educational Note:",
    "xss.prevention": "Prevention:",
    "xss.payloads_title": "Try These XSS Payloads:",
    "xss.basic_script": "Basic script:",
    "xss.image_onerror": "Image onerror:",
    "xss.javascript_url": "JavaScript URL:",
    "xss.event_handler": "Event handler:",
    "xss.svg_payload": "SVG payload:",
    "xss.body_onload": "Body onload:",
    "xss.educational_purpose": "Educational Purpose Only: These payloads are for learning. Never use them on systems you don't own or without explicit permission.",
    "xss.basic_html_encoding": "Basic HTML encoding applied. Script tags are escaped, but this protection can sometimes be bypassed with other XSS vectors.",
    "xss.medium_html_encoding": "Medium level applies basic HTML encoding but may still be vulnerable to attribute-based XSS.",
    "xss.hard_sanitization": "Hard level uses comprehensive input sanitization, making XSS very difficult.",
    "xss.prevention_csp": "Use Content Security Policy (CSP), encode output, and validate/sanitize all user input.",
    
    // Command Injection Module
    "command_injection.title": "Command Injection",
    "command_injection.description": "Learn about command injection vulnerabilities in web applications.",
    "command_injection.network_ping": "Network Ping Utility",
    "command_injection.host_ip": "Host/IP Address",
    "command_injection.host_placeholder": "Enter host or IP address to ping...",
    "command_injection.execute_ping": "Execute Ping",
    "command_injection.executing": "Executing...",
    "command_injection.command_results": "Command Results",
    "command_injection.executed_command": "Executed Command:",
    "command_injection.command_output": "Command Output:",
    "command_injection.payloads_title": "Try These Payloads:",
    "command_injection.command_chaining": "Command chaining:",
    "command_injection.logical_and": "Logical AND:",
    "command_injection.pipe_operator": "Pipe operator:",
    "command_injection.background_execution": "Background execution:",
    "command_injection.semicolon_successful": "Command injection successful! The semicolon allowed execution of additional commands, exposing sensitive system files.",
    "command_injection.and_operator_successful": "Command injection via && operator successful! This reveals the current user context.",
    "command_injection.medium_filtering": "Medium level applies basic filtering. Try alternative operators: ||, `, $(), etc.",
    
    // CSRF Module
    "csrf.title": "CSRF Protection", 
    "csrf.description": "Learn about Cross-Site Request Forgery attacks and defenses.",
    "csrf.profile_update": "Profile Update Form",
    "csrf.email_address": "Email Address",
    "csrf.email_placeholder": "Enter your email address...",
    "csrf.new_password": "New Password",
    "csrf.password_placeholder": "Enter new password...",
    "csrf.csrf_token": "CSRF Token:",
    "csrf.update_profile": "Update Profile",
    "csrf.updating": "Updating...",
    "csrf.form_analysis": "Form Analysis",
    "csrf.generated_form": "Generated Form HTML:",
    "csrf.csrf_attack": "Potential CSRF Attack:",
    "csrf.security_analysis": "Security Analysis:",
    "csrf.protection_methods": "CSRF Protection Methods:",
    "csrf.anti_csrf_tokens": "✓ Anti-CSRF Tokens",
    "csrf.anti_csrf_desc": "Include unique, unpredictable tokens in forms",
    "csrf.samesite_cookies": "✓ SameSite Cookies",
    "csrf.samesite_desc": "Prevent cookies from being sent in cross-site requests", 
    "csrf.referrer_validation": "✓ Referrer Validation",
    "csrf.referrer_desc": "Check that requests come from expected origins",
    "csrf.double_submit": "✓ Double Submit Pattern",
    "csrf.double_submit_desc": "Send token in both cookie and form field",
    
    // SQL Injection Module
    "sql_injection.title": "SQL Injection",
    "sql_injection.description": "Learn how SQL injection vulnerabilities work and how to exploit them safely.",
    "sql_injection.user_lookup": "User Lookup System", 
    "sql_injection.querying": "Querying...",
    "sql_injection.executed_query": "Executed Query:",
    "sql_injection.retrieved_data": "Retrieved Data:",
    "sql_injection.no_results": "No results found for the given input.",
    "sql_injection.educational_note": "Educational Note:",
    "sql_injection.prevention": "Prevention:",
    "sql_injection.payloads_title": "Try These Payloads:",
    "sql_injection.basic_bypass": "Basic bypass:",
    "sql_injection.comment_injection": "Comment injection:",
    "sql_injection.union_attack": "UNION attack:",
    "sql_injection.boolean_based": "Boolean-based:",
    "sql_injection.sqli_successful": "SQL injection successful! The query returned all users because '1'='1' is always true, bypassing the WHERE condition.",
    "sql_injection.union_sqli_successful": "UNION-based SQL injection successful! Additional data was retrieved from the database.",
    "sql_injection.medium_sanitization": "Medium level applies basic sanitization but may still be vulnerable to other SQL injection techniques.",
    "sql_injection.hard_sanitization": "Hard level uses advanced input sanitization, making SQL injection very difficult.",
    
    // File Inclusion Module
    "file_inclusion.title": "File Inclusion",
    "file_inclusion.description": "Learn about Local and Remote File Inclusion vulnerabilities",
    "file_inclusion.file_viewer": "File Viewer Application",
    "file_inclusion.file_viewer_desc": "Enter a filename to include and display its contents",
    "file_inclusion.file_to_include": "File to include:",
    "file_inclusion.file_placeholder": "Enter filename (e.g., home.php, ../../../etc/passwd)",
    "file_inclusion.include_file": "Include File",
    "file_inclusion.loading": "Loading...",
    "file_inclusion.analysis": "File Inclusion Analysis",
    "file_inclusion.requested_file": "Requested File:",
    "file_inclusion.file_contents": "File Contents:",
    "file_inclusion.security_analysis": "Security Analysis:",
    "file_inclusion.prevention_methods": "Prevention Methods:",
    "file_inclusion.common_payloads": "Common File Inclusion Payloads",
    "file_inclusion.path_traversal": "Path Traversal (LFI):",
    "file_inclusion.php_wrappers": "PHP Wrappers:",
    "file_inclusion.path_traversal_successful": "Path traversal attack successful!",
    "file_inclusion.file_included_successfully": "✅ File included successfully",
    "file_inclusion.filter_bypass_successful": "Filter bypass successful!",
    
    // Auth Bypass Module
    "auth_bypass.title": "Authentication Bypass",
    "auth_bypass.description": "Learn about authentication bypass techniques and vulnerabilities",
    "auth_bypass.login_system": "Login System",
    "auth_bypass.login_desc": "Enter credentials to access the system",
    "auth_bypass.username": "Username",
    "auth_bypass.password": "Password",
    "auth_bypass.login": "Login",
    "auth_bypass.logging_in": "Logging in...",
    "auth_bypass.auth_analysis": "Authentication Analysis",
    "auth_bypass.attempted_credentials": "Attempted Credentials:",
    "auth_bypass.auth_result": "Authentication Result:",
    "auth_bypass.session_info": "Session Information:",
    "auth_bypass.security_analysis": "Security Analysis:",
    "auth_bypass.prevention_methods": "Prevention Methods:",
    "auth_bypass.common_bypasses": "Common Bypass Techniques",
    "auth_bypass.sql_injection": "SQL Injection:",
    "auth_bypass.logic_flaws": "Logic Flaws:",
    "auth_bypass.sql_injection_successful": "SQL Injection successful!",
    "auth_bypass.case_sensitivity_bypass": "Case sensitivity bypass successful!",
    "auth_bypass.secure_auth_successful": "✅ Secure authentication successful",
    
    // Brute Force Module
    "brute_force.title": "Brute Force Attack",
    "brute_force.description": "Learn about brute force attacks and protection mechanisms",
    "brute_force.attack_simulator": "Brute Force Attack Simulator",
    "brute_force.attack_desc": "Simulate a brute force attack against a login system",
    "brute_force.target_username": "Target Username",
    "brute_force.start_attack": "Start Brute Force Attack",
    "brute_force.attacking": "Attacking...",
    "brute_force.attack_progress": "Attack Progress:",
    "brute_force.current_attempt": "Current Attempt:",
    "brute_force.attack_results": "Attack Results",
    "brute_force.total_attempts": "Total Attempts:",
    "brute_force.time_taken": "Time Taken:",
    "brute_force.attack_status": "Attack Status:",
    "brute_force.found_password": "Found Password:",
    "brute_force.common_passwords": "Common Passwords to Try:",
    "brute_force.attack_successful": "Brute force attack successful!",
    "brute_force.attack_successful_rate_limited": "Brute force successful despite rate limiting!",
    
    // File Upload Module
    "file_upload.title": "File Upload Vulnerability",
    "file_upload.description": "Learn about file upload vulnerabilities and bypass techniques",
    "file_upload.uploader": "File Upload System",
    "file_upload.uploader_desc": "Upload files to the server (images only)",
    "file_upload.choose_file": "Choose file",
    "file_upload.upload": "Upload File",
    "file_upload.uploading": "Uploading...",
    "file_upload.upload_results": "Upload Results",
    "file_upload.filename": "Filename:",
    "file_upload.file_size": "File Size:",
    "file_upload.file_type": "File Type:",
    "file_upload.upload_status": "Upload Status:",
    "file_upload.upload_bypasses": "File Upload Bypasses",
    "file_upload.extension_bypass": "Extension Bypass:",
    "file_upload.mime_bypass": "MIME Type Bypass:",
    "file_upload.double_extension": "Double Extension:",
    "file_upload.malicious_uploaded_successfully": "Malicious file uploaded successfully!",
    "file_upload.file_uploaded_successfully": "✅ File uploaded successfully",
    "file_upload.double_extension_bypass": "Double extension bypass successful!",
    
    // Insecure Captcha Module
    "insecure_captcha.title": "Insecure CAPTCHA",
    "insecure_captcha.description": "Learn about CAPTCHA bypass techniques and vulnerabilities",
    "insecure_captcha.login_captcha": "Login with CAPTCHA",
    "insecure_captcha.login_desc": "Complete the CAPTCHA to proceed with login",
    "insecure_captcha.captcha_code": "CAPTCHA Code",
    "insecure_captcha.enter_captcha": "Enter the CAPTCHA code shown above",
    "insecure_captcha.refresh_captcha": "Refresh CAPTCHA",
    "insecure_captcha.submit": "Submit",
    "insecure_captcha.verifying": "Verifying...",
    "insecure_captcha.captcha_results": "CAPTCHA Verification Results",
    "insecure_captcha.captcha_value": "CAPTCHA Value:",
    "insecure_captcha.user_input": "User Input:",
    "insecure_captcha.verification_result": "Verification Result:",
    "insecure_captcha.bypass_techniques": "CAPTCHA Bypass Techniques",
    "insecure_captcha.client_side": "Client-side Validation:",
    "insecure_captcha.predictable": "Predictable Values:",
    "insecure_captcha.reuse": "Session Reuse:",
    
    // Weak Session Module
    "weak_session.title": "Weak Session IDs",
    "weak_session.description": "Learn about session management vulnerabilities and attacks",
    "weak_session.session_manager": "Session Manager",
    "weak_session.session_desc": "Generate and analyze session IDs",
    "weak_session.generate_session": "Generate Session ID",
    "weak_session.generating": "Generating...",
    "weak_session.session_analysis": "Session ID Analysis",
    "weak_session.generated_id": "Generated Session ID:",
    "weak_session.entropy": "Entropy Level:",
    "weak_session.predictability": "Predictability:",
    "weak_session.session_attacks": "Session ID Attack Patterns",
    "weak_session.sequential": "Sequential IDs:",
    "weak_session.timestamp": "Timestamp-based:",
    "weak_session.brute_force": "Brute Force:",
    "weak_session.pattern_analysis": "Requires pattern analysis",
    "weak_session.hash_collision": "Hash collision possible", 
    "weak_session.time_prediction": "Time-based prediction",
    
    // Insecure Captcha Additional Keys
    "insecure_captcha.password_updated": "🔒 Password updated successfully",
    "insecure_captcha.captcha_verified": "✅ CAPTCHA verified successfully",
    "insecure_captcha.password_changed": "Password Changed Successfully",
    
    // OWASP Top 10 Module
    "owasp_top10.title": "OWASP Top 10",
    "owasp_top10.description": "Learn about the top 10 web application security vulnerabilities",
    "owasp_top10.current_year": "OWASP Top 10 - 2023",
    "owasp_top10.vulnerability_list": "Vulnerability List",
    "owasp_top10.details": "Vulnerability Details",
    "owasp_top10.examples": "Practical Examples",
    "owasp_top10.mitigation": "Mitigation Strategies",
    
    // Secure Coding Module
    "secure_coding.title": "Secure Coding",
    "secure_coding.description": "Learn secure development practices and vulnerability prevention",
    "secure_coding.best_practices": "Best Practices",
    "secure_coding.code_review": "Code Review",
    "secure_coding.static_analysis": "Static Analysis",
    "secure_coding.dynamic_testing": "Dynamic Testing",
    "secure_coding.secure_patterns": "Secure Patterns",
    
    // Threat Modeling Module
    "threat_modeling.title": "Threat Modeling",
    "threat_modeling.description": "Learn to systematically identify and mitigate security threats",
    "threat_modeling.methodology": "STRIDE Methodology",
    "threat_modeling.threat_identification": "Threat Identification",
    "threat_modeling.risk_assessment": "Risk Assessment",
    "threat_modeling.mitigation_strategies": "Mitigation Strategies",
    
    // Injection Attacks Module
    "injection_attacks.title": "Injection Attacks",
    "injection_attacks.description": "Learn about different types of injection attacks and their defenses",
    "injection_attacks.sql_injection": "SQL Injection",
    "injection_attacks.command_injection": "Command Injection",
    "injection_attacks.ldap_injection": "LDAP Injection",
    "injection_attacks.xpath_injection": "XPath Injection",
    "injection_attacks.prevention": "Prevention Techniques",
    
    // Authentication Module
    "authentication.title": "Authentication",
    "authentication.description": "Learn about secure authentication systems and their implementations",
    "authentication.multi_factor": "Multi-Factor Authentication",
    "authentication.password_policies": "Password Policies",
    "authentication.biometric_auth": "Biometric Authentication",
    "authentication.oauth_saml": "OAuth and SAML",
    "authentication.best_practices": "Best Practices",
    
    // Session Management Module
    "session_management.title": "Session Management",
    "session_management.description": "Learn about secure user session management",
    "session_management.session_lifecycle": "Session Lifecycle",
    "session_management.token_management": "Token Management",
    "session_management.session_security": "Session Security",
    "session_management.session_attacks": "Session Attacks",
    
    // Network Protocols Module
    "network_protocols.title": "Network Protocols",
    "network_protocols.description": "Learn about network protocol security",
    "network_protocols.tcp_ip": "TCP/IP Security",
    "network_protocols.tls_ssl": "TLS/SSL",
    "network_protocols.dns_security": "DNS Security",
    "network_protocols.vpn": "VPN and Tunneling",
    
    // Firewalls Module
    "firewalls.title": "Firewalls",
    "firewalls.description": "Learn about firewall configuration and management",
    "firewalls.packet_filtering": "Packet Filtering",
    "firewalls.stateful_inspection": "Stateful Inspection",
    "firewalls.application_layer": "Application Layer Firewall",
    "firewalls.rule_configuration": "Rule Configuration",
    
    // Encryption Module
    "encryption.title": "Encryption",
    "encryption.description": "Learn about cryptography and data protection techniques",
    "encryption.symmetric_crypto": "Symmetric Cryptography",
    "encryption.asymmetric_crypto": "Asymmetric Cryptography",
    "encryption.hashing": "Hash Functions",
    "encryption.digital_signatures": "Digital Signatures",
    "encryption.key_management": "Key Management",
    
    // Linux Security Module
    "linux_security.title": "Linux Security",
    "linux_security.description": "Learn about Linux system security",
    "linux_security.user_management": "User Management",
    "linux_security.file_permissions": "File Permissions",
    "linux_security.selinux": "SELinux",
    "linux_security.system_hardening": "System Hardening",
    "linux_security.log_monitoring": "Log Monitoring",
    
    // Windows Security Module
    "windows_security.title": "Windows Security",
    "windows_security.description": "Learn about Windows system security",
    "windows_security.active_directory": "Active Directory",
    "windows_security.group_policy": "Group Policy",
    "windows_security.windows_defender": "Windows Defender",
    "windows_security.powershell_security": "PowerShell Security",
    
    // macOS Security Module
    "macos_security.title": "macOS Security",
    "macos_security.description": "Learn about macOS system security",
    "macos_security.gatekeeper": "Gatekeeper",
    "macos_security.system_integrity": "System Integrity Protection",
    "macos_security.keychain": "Keychain",
    "macos_security.xprotect": "XProtect",
    
    // Container Security Module
    "container_security.title": "Container Security",
    "container_security.description": "Learn about security in containerized environments",
    "container_security.docker_security": "Docker Security",
    "container_security.kubernetes_security": "Kubernetes Security",
    "container_security.image_scanning": "Image Scanning",
    "container_security.runtime_security": "Runtime Security",
    
    // Python Security Module
    "python_security.title": "Python Security",
    "python_security.description": "Learn about security practices in Python development",
    "python_security.secure_coding": "Secure Coding",
    "python_security.dependency_management": "Dependency Management",
    "python_security.web_framework_security": "Web Framework Security",
    "python_security.serialization": "Serialization Security",
    
    // JavaScript Security Module
    "javascript_security.title": "JavaScript Security",
    "javascript_security.description": "Learn about security in JavaScript development",
    "javascript_security.client_side": "Client-side Security",
    "javascript_security.nodejs_security": "Node.js Security",
    "javascript_security.package_security": "Package Security",
    "javascript_security.prototype_pollution": "Prototype Pollution",
    
    // C/C++ Security Module
    "c_cpp_security.title": "C/C++ Security",
    "c_cpp_security.description": "Learn about security in C/C++ development",
    "c_cpp_security.memory_management": "Memory Management",
    "c_cpp_security.buffer_overflow": "Buffer Overflow",
    "c_cpp_security.static_analysis": "Static Analysis",
    "c_cpp_security.secure_functions": "Secure Functions",
    
    // Java Security Module
    "java_security.title": "Java Security",
    "java_security.description": "Learn about security in Java development",
    "java_security.jvm_security": "JVM Security",
    "java_security.serialization_attacks": "Serialization Attacks",
    "java_security.spring_security": "Spring Security",
    "java_security.secure_coding": "Secure Coding",
    
    // Assembly Security Module
    "assembly_security.title": "Assembly Security",
    "assembly_security.description": "Learn about security in Assembly programming and low-level analysis",
    "assembly_security.reverse_engineering": "Reverse Engineering",
    "assembly_security.exploit_development": "Exploit Development",
    "assembly_security.binary_analysis": "Binary Analysis",
    "assembly_security.shellcode": "Shellcode",
    
    // Chat Bot Messages
    "chat.greeting_morning": "Good morning",
    "chat.greeting_afternoon": "Good afternoon", 
    "chat.greeting_evening": "Good evening",
    "chat.assistant_intro": "I'm your CyberLab Security Assistant. 🛡️",
    "chat.working_on_challenge": "I see you're working on the {module} challenge.",
    "chat.difficulty_level": "This is a {difficulty} level challenge.",
    "chat.can_help_with": "I can help you with:",
    "chat.help_topics": "• Vulnerability exploitation techniques\n• Payload suggestions and examples\n• Troubleshooting common errors\n• Security best practices",
    "chat.what_explore": "What would you like to explore today?",
    "chat.based_on_module": "Based on your current module, you might want to try:",
    "chat.sql_injection_help": "Here are some SQL injection payloads to try:",
    "chat.sql_remember": "Remember to URL-encode special characters when testing in a browser. Start with the basic OR condition and work your way up to more complex UNION attacks.",
    "chat.xss_help": "Here are some XSS payloads to test:",
    "chat.xss_try_contexts": "Try these in different contexts - URL parameters, form fields, and headers. If one doesn't work, try the others!",
    "chat.command_injection_help": "Here are command injection payloads:",
    "chat.command_start_simple": "Start with simple commands like `whoami` or `ls` to verify injection works, then try more complex commands.",
    "chat.troubleshoot_help": "I can help you troubleshoot! Here are some common issues and solutions:",
    "chat.common_issues": "• **SQL Syntax Error**: Check quote placement and comment syntax\n• **Script Not Executing**: Try different XSS contexts or bypass CSP\n• **Command Not Found**: Verify the command exists on the target system\n• **Access Denied**: You may need different privileges or file paths",
    "chat.share_error": "Can you share the specific error message you're seeing?",
    "chat.contextual_suggestions": "Based on your current challenge, here are some suggestions:",
    "chat.want_payloads": "Would you like specific payloads for any of these techniques?",
    "chat.found_info": "I found information about **{name}**:",
    "chat.try_payloads": "Here are some payloads to try:",
    "chat.found_challenge": "I found the **{name}** challenge. Here are some hints:",
    "chat.default_help": "I'm here to help with your cybersecurity challenges! You can ask me about:\n\n• Specific vulnerabilities (SQL injection, XSS, etc.)\n• Payload examples and techniques\n• Troubleshooting errors\n• Security best practices",
    "chat.payloads_copied": "✅ Payloads copied to clipboard!",
    "chat.copy_failed": "❌ Failed to copy payloads. Please copy them manually.",
    "chat.thinking": "Thinking...",
    "chat.online_ready": "Online • Ready to help",
    "chat.clear_history": "Clear chat history",
    "chat.copy_message": "Copy message",
    "chat.mark_helpful": "Mark as helpful",
    "chat.mark_not_helpful": "Mark as not helpful",
    "chat.export_payloads": "Export Payloads",
    "chat.ask_placeholder": "Ask about vulnerabilities, payloads, or techniques...",
    "chat.send_instruction": "Press Enter to send • Shift+Enter for new line",
    "chat.security_assistant": "Security Assistant",
  },
  "pt-BR": {
    "header.subtitle": "Plataforma Interativa de Aprendizado em Segurança Web",
    "header.light": "Claro",
    "header.dark": "Escuro",
    "sidebar.difficulty": "Nível de Segurança",
    "sidebar.modules": "Módulos de Aprendizado",
    "sidebar.status": "Status da Sessão",
    "sidebar.current": "Módulo",
    "sidebar.level": "Nível",
    "difficulty.easy": "Fácil",
    "difficulty.low": "Baixo",
    "difficulty.medium": "Médio",
    "difficulty.hard": "Difícil", 
    "difficulty.high": "Alto",
    "difficulty.impossible": "Impossível",
    "security.low": "Baixo",
    "security.medium": "Médio",
    "security.high": "Alto",
    "security.level": "Nível de Segurança",
    "modules.home": "Início",
    "modules.sql-injection": "Injeção SQL",
    "modules.sql-blind": "Injeção SQL (Blind)",
    "modules.xss": "Cross-Site Scripting",
    "modules.command-injection": "Injeção de Comando",
    "modules.csrf": "Proteção CSRF",
    "modules.file-inclusion": "Inclusão de Arquivo",
    "modules.auth-bypass": "Bypass de Autenticação",
    "modules.brute-force": "Força Bruta",
    "modules.file-upload": "Upload de Arquivo",
    "modules.insecure-captcha": "CAPTCHA Inseguro",
    "modules.weak-session": "IDs de Sessão Fracos",
    "modules.totp-2fa": "Autenticação TOTP/2FA",
    "modules.jwt-authentication": "Autenticação JWT",
    "modules.coming_soon": "Módulo em breve...",
    "modules.learn": "Aprender",
    "learn.mode": "Modo Aprendizado",
    "learn.guided": "Aprendizado Guiado",
    "learn.fundamentals": "Fundamentos de Segurança",
    "learn.web_security": "Segurança Web",
    "learn.network_security": "Segurança de Rede",
    "learn.os_security": "Segurança de Sistemas Operacionais",
    "learn.programming_security": "Programação Segura",
    "home.title": "Bem-vindo ao CyberLab",
    "home.subtitle": "Plataforma Interativa de Aprendizado em Segurança Web",
    "home.description": "O CyberLab é uma plataforma educacional interativa projetada para ensinar e treinar segurança web em um ambiente controlado e seguro. O objetivo desta plataforma é capacitar estudantes, desenvolvedores e profissionais de segurança a aprender, explorar e compreender vulnerabilidades comuns de aplicações web através da prática prática.",
    "home.get_started": "Começar",
    "home.general_instructions": "Instruções Gerais",
    "home.general_instructions_content": "Os usuários podem explorar os módulos em qualquer ordem, dependendo do seu nível de conhecimento. Cada módulo inclui teoria, exemplos práticos e desafios interativos, permitindo que os usuários validem suas tentativas de exploração. O sistema também contém cenários ocultos e não documentados para encorajar a curiosidade e promover abordagens de pentesting mais criativas. Um modo de aprendizado está disponível com dicas, tutoriais e referências adicionais.",
    "home.warning": "AVISO!",
    "home.warning_content": "O CyberLab é uma plataforma deliberadamente vulnerável, criada exclusivamente para fins educacionais. NÃO deve ser implantada em servidores de produção ou exposta à internet pública, pois isso pode comprometer a segurança do ambiente. É fortemente recomendado executar o CyberLab em máquinas virtuais isoladas ou outros ambientes de laboratório controlados.",
    "home.disclaimer": "Isenção de Responsabilidade",
    "home.disclaimer_content": "Os desenvolvedores do CyberLab não assumem responsabilidade por qualquer uso indevido da plataforma. Este sistema deve ser usado apenas para fins de aprendizado e de acordo com práticas éticas e legais.",
    "home.features.interactive": "Aprendizado Interativo",
    "home.features.interactive_desc": "Pratique com vulnerabilidades reais",
    "home.features.multilingual": "Suporte Multilíngue",
    "home.features.multilingual_desc": "Disponível em múltiplos idiomas",
    "home.features.difficulty": "Dificuldade Progressiva",
    "home.features.difficulty_desc": "Do iniciante ao nível expert",
    "sql.title": "Injeção SQL",
    "sql.description": "Aprenda como funcionam as vulnerabilidades de injeção SQL e como explorá-las com segurança.",
    "sql.user_id": "ID do Usuário",
    "sql.submit": "Consultar Banco",
    "sql.results": "Resultados da Consulta",
    "sql.placeholder": "Digite o ID do usuário para buscar...",
    "xss.title": "Cross-Site Scripting (XSS)",
    "xss.description": "Entenda vulnerabilidades XSS e pratique explorá-las.",
    "xss.message": "Mensagem",
    "xss.submit": "Enviar Mensagem",
    "xss.results": "Exibição da Mensagem",
    "xss.placeholder": "Digite sua mensagem...",
    "command.search": "Pesquisar módulos...",
    "command.no_results": "Nenhum resultado encontrado.",
    "command.navigation": "Navegação",
    "command.categories": "Categorias de Aprendizado",
    "command.topics": "Tópicos de Aprendizado",
    
    // Learn Mode
    "learn.category_not_found": "Categoria Não Encontrada",
    "learn.category_not_found_desc": "A categoria de aprendizado solicitada não existe.",
    "learn.progress": "Progresso",
    "learn.lessons": "lições",
    "learn.completed": "completas",
    "learn.lesson_sections": "Seções da Lição",
    "learn.previous_section": "Seção Anterior",
    "learn.next_section": "Próxima Seção",
    "learn.key_points": "Pontos Principais",
    "learn.code_examples": "Exemplos de Código",
    "learn.vulnerable_code": "Código Vulnerável",
    "learn.secure_code": "Código Seguro",
    "learn.vulnerable_implementation": "Implementação Vulnerável",
    "learn.secure_implementation": "Implementação Segura",
    "learn.why_vulnerable": "Por que é vulnerável:",
    "learn.why_secure": "Por que é seguro:",
    "learn.prevention_strategies": "Estratégias de Prevenção",
    "learn.theory": "Teoria",
    "learn.practical": "Prático",
    "learn.security_fundamentals_desc": "Conceitos e princípios essenciais de segurança",
    "learn.web_security_desc": "Práticas de segurança em aplicações web",
    "learn.network_security_desc": "Proteção de rede e protocolos",
    "learn.understanding": "Compreendendo",
    "learn.secure_development": "Desenvolvimento Seguro",
    "learn.protection_and": "Proteção e",
    
    // 404 Page
    "notfound.title": "Página Não Encontrada",
    "notfound.description": "A página que você está procurando não existe ou foi movida.",
    "notfound.return_home": "Voltar ao Início",
    
    // SQL Blind Module
    "sql_blind.title": "SQL Injection (Blind)",
    "sql_blind.description": "Aprenda sobre técnicas de injeção SQL blind e métodos de exploração.",
    "sql_blind.user_id": "ID do Usuário",
    "sql_blind.search_user": "Buscar Usuário",
    "sql_blind.querying": "Consultando...",
    "sql_blind.analysis_results": "Resultados da Análise - Técnica:",
    "sql_blind.query": "Consulta:",
    "sql_blind.response": "Resposta:",
    "sql_blind.response_time": "Tempo de Resposta:",
    "sql_blind.suspicious_delay": "Delay suspeito!",
    "sql_blind.analysis_notes": "Notas da Análise",
    "sql_blind.prevention_measures": "Medidas de Prevenção",
    "sql_blind.payloads_title": "🎯 Payloads de Blind SQL Injection:",
    "sql_blind.boolean_based": "Baseado em Boolean:",
    "sql_blind.time_based_mysql": "Baseado em tempo (MySQL):",
    "sql_blind.time_based_sqlserver": "Baseado em tempo (SQL Server):",
    "sql_blind.data_extraction": "Extração de dados:",
    "sql_blind.boolean_blind_technique": "Boolean-based Blind",
    "sql_blind.time_based_blind_technique": "Time-based Blind",
    "sql_blind.boolean_limited_technique": "Boolean-based (Limitado)",
    "sql_blind.boolean_injection_successful": "Injeção blind baseada em boolean bem-sucedida!",
    "sql_blind.time_injection_successful": "Injeção blind baseada em tempo bem-sucedida!",
    "sql_blind.boolean_vulnerability_confirmed": "Isso confirma vulnerabilidade de injeção blind baseada em boolean",
    "sql_blind.time_techniques_effective": "Técnicas baseadas em tempo podem ser mais eficazes",
    "sql_blind.boolean_blind_description": " - Injeção blind baseada em boolean",
    "sql_blind.time_blind_description": " - Injeção blind baseada em tempo",
    "sql_blind.advanced_blind_description": " - Técnicas blind avançadas",
    "sql_blind.input_validation_implemented": "✓ Validação de entrada implementada",
    "sql_blind.proper_error_handling": "✓ Tratamento adequado de erros",
    "sql_blind.implement_input_validation": "Implementar validação adequada de entrada",
    "sql_blind.add_query_timeouts": "Adicionar timeouts de consulta para prevenir ataques baseados em tempo",
    "sql_blind.implement_error_handling": "Implementar tratamento adequado de erros",
    "sql_blind.try_time_based_payloads": "Experimente payloads baseados em tempo: ' AND SLEEP(5)-- ou condições boolean",
    
    // TOTP/2FA Authentication Module
    "totp.title": "Autenticação TOTP/2FA",
    "totp.description": "Aprenda sobre implementação de autenticação de dois fatores com TOTP",
    "totp.enable_2fa": "Ativar Autenticação de Dois Fatores",
    "totp.qr_code_instruction": "Escaneie este QR code com seu app autenticador",
    "totp.secret_key": "Chave secreta:",
    "totp.enter_code": "Digite o código de 6 dígitos do seu app autenticador",
    "totp.verify_code": "Verificar Código",
    "totp.login_attempts": "Tentativas de Login",
    "totp.easy_level": "Fácil - Token Previsível",
    "totp.medium_level": "Médio - Validação Falha",
    "totp.hard_level": "Difícil - Vazamento Criptográfico",
    "totp.exploitation_tips": "Dicas de Exploração:",
    "totp.weak_secret": "Secret fraco e janela de tempo longa",
    "totp.no_rate_limiting": "Sem limitação de tentativas",
    "totp.secret_exposure": "Secret exposto em respostas",
    
    // JWT Authentication Module
    "jwt.title": "Autenticação JWT",
    "jwt.description": "Aprenda sobre vulnerabilidades em implementações JWT",
    "jwt.login_generate": "Login & Gerar JWT",
    "jwt.current_token": "Token Atual",
    "jwt.decoded_payload": "Payload Decodificado",
    "jwt.custom_token_test": "Teste de Token Personalizado",
    "jwt.validate_token": "Validar Token",
    "jwt.public_key_endpoint": "Endpoint de Chave Pública",
    "jwt.jku_configuration": "Configuração JKU Header",
    "jwt.malicious_jku_url": "URL JKU Maliciosa",
    "jwt.easy_level": "Fácil - Algoritmo None",
    "jwt.medium_level": "Médio - Confusão de Algoritmo",
    "jwt.hard_level": "Difícil - Injeção JKU Header",
    "jwt.none_algorithm": "Aceita algoritmo 'none'",
    "jwt.algorithm_confusion": "Confusão de algoritmo",
    "jwt.jku_injection": "Injeção JKU header",
    "jwt.exploitation_steps": "Passos de Exploração:",
    "jwt.load_example": "Carregar Token de Exemplo",
    
    // XSS Module  
    "xss.message_board": "Sistema de Quadro de Mensagens",
    "xss.processing": "Processando...",
    "xss.message_preview": "Visualização da Mensagem:",
    "xss.security_analysis": "Análise de Segurança",
    "xss.original_input": "Entrada Original:",
    "xss.processed_output": "Saída Processada:",
    "xss.educational_note": "Nota Educacional:",
    "xss.prevention": "Prevenção:",
    "xss.payloads_title": "💡 Experimente Estes Payloads XSS:",
    "xss.basic_script": "Script básico:",
    "xss.image_onerror": "Image onerror:",
    "xss.javascript_url": "JavaScript URL:",
    "xss.event_handler": "Manipulador de evento:",
    "xss.svg_payload": "Payload SVG:",
    "xss.body_onload": "Body onload:",
    "xss.educational_purpose": "Apenas Para Fins Educacionais: Estes payloads são para aprendizado. Nunca os use em sistemas que você não possui ou sem permissão explícita.",
    "xss.basic_html_encoding": "Codificação HTML básica aplicada. Tags script são escapadas, mas esta proteção às vezes pode ser contornada com outros vetores XSS.",
    "xss.medium_html_encoding": "O nível médio aplica codificação HTML básica, mas ainda pode ser vulnerável a XSS baseado em atributos.",
    "xss.hard_sanitization": "O nível difícil usa sanitização abrangente de entrada, tornando XSS muito difícil.",
    "xss.prevention_csp": "Use Content Security Policy (CSP), codifique saídas e valide/sanitize todas as entradas do usuário.",
    
    // Command Injection Module
    "command_injection.title": "Command Injection",
    "command_injection.description": "Aprenda sobre vulnerabilidades de injeção de comando em aplicações web.",
    "command_injection.network_ping": "Utilitário de Ping de Rede",
    "command_injection.host_ip": "Host/Endereço IP",
    "command_injection.host_placeholder": "Digite o host ou endereço IP para ping...",
    "command_injection.execute_ping": "Executar Ping",
    "command_injection.executing": "Executando...",
    "command_injection.command_results": "Resultados do Comando",
    "command_injection.executed_command": "Comando Executado:",
    "command_injection.command_output": "Saída do Comando:",
    "command_injection.payloads_title": "💡 Experimente Estes Payloads:",
    "command_injection.command_chaining": "Encadeamento de comandos:",
    "command_injection.logical_and": "AND lógico:",
    "command_injection.pipe_operator": "Operador pipe:",
    "command_injection.background_execution": "Execução em background:",
    "command_injection.semicolon_successful": "Injeção de comando bem-sucedida! O ponto e vírgula permitiu a execução de comandos adicionais, expondo arquivos sensíveis do sistema.",
    "command_injection.and_operator_successful": "Injeção de comando via operador && bem-sucedida! Isso revela o contexto do usuário atual.",
    "command_injection.medium_filtering": "Nível médio aplica filtragem básica. Tente operadores alternativos: ||, `, $(), etc.",
    
    // CSRF Module
    "csrf.title": "Proteção CSRF", 
    "csrf.description": "Aprenda sobre ataques Cross-Site Request Forgery e defesas.",
    "csrf.profile_update": "Formulário de Atualização de Perfil",
    "csrf.email_address": "Endereço de Email",
    "csrf.email_placeholder": "Digite seu endereço de email...",
    "csrf.new_password": "Nova Senha",
    "csrf.password_placeholder": "Digite a nova senha...",
    "csrf.csrf_token": "Token CSRF:",
    "csrf.update_profile": "Atualizar Perfil",
    "csrf.updating": "Atualizando...",
    "csrf.form_analysis": "Análise do Formulário",
    "csrf.generated_form": "HTML do Formulário Gerado:",
    "csrf.csrf_attack": "Possível Ataque CSRF:",
    "csrf.security_analysis": "Análise de Segurança:",
    "csrf.protection_methods": "🛡️ Métodos de Proteção CSRF:",
    "csrf.anti_csrf_tokens": "✓ Tokens Anti-CSRF",
    "csrf.anti_csrf_desc": "Inclua tokens únicos e imprevisíveis em formulários",
    "csrf.samesite_cookies": "✓ Cookies SameSite",
    "csrf.samesite_desc": "Previne que cookies sejam enviados em requisições cross-site", 
    "csrf.referrer_validation": "✓ Validação de Referrer",
    "csrf.referrer_desc": "Verifica se as requisições vêm de origens esperadas",
    "csrf.double_submit": "✓ Padrão Double Submit",
    "csrf.double_submit_desc": "Envia token tanto no cookie quanto no campo do formulário",
    
    // SQL Injection Module
    "sql_injection.title": "Injeção SQL",
    "sql_injection.description": "Aprenda como funcionam as vulnerabilidades de injeção SQL e como explorá-las com segurança.",
    "sql_injection.user_lookup": "Sistema de Busca de Usuário", 
    "sql_injection.querying": "Consultando...",
    "sql_injection.executed_query": "Consulta Executada:",
    "sql_injection.retrieved_data": "Dados Recuperados:",
    "sql_injection.no_results": "Nenhum resultado encontrado para a entrada fornecida.",
    "sql_injection.educational_note": "Nota Educacional:",
    "sql_injection.prevention": "Prevenção:",
    "sql_injection.payloads_title": "💡 Experimente Estes Payloads:",
    "sql_injection.basic_bypass": "Bypass básico:",
    "sql_injection.comment_injection": "Injeção de comentário:",
    "sql_injection.union_attack": "Ataque UNION:",
    "sql_injection.boolean_based": "Baseado em Boolean:",
    
    // File Inclusion Module
    "file_inclusion.title": "Inclusão de Arquivo",
    "file_inclusion.description": "Aprenda sobre vulnerabilidades de Inclusão Local e Remota de Arquivos",
    "file_inclusion.file_viewer": "Aplicação Visualizadora de Arquivos",
    "file_inclusion.file_viewer_desc": "Digite um nome de arquivo para incluir e exibir seu conteúdo",
    "file_inclusion.file_to_include": "Arquivo para incluir:",
    "file_inclusion.file_placeholder": "Digite o nome do arquivo (ex: home.php, ../../../etc/passwd)",
    "file_inclusion.include_file": "Incluir Arquivo",
    "file_inclusion.loading": "Carregando...",
    "file_inclusion.analysis": "Análise de Inclusão de Arquivo",
    "file_inclusion.requested_file": "Arquivo Solicitado:",
    "file_inclusion.file_contents": "Conteúdo do Arquivo:",
    "file_inclusion.security_analysis": "Análise de Segurança:",
    "file_inclusion.prevention_methods": "Métodos de Prevenção:",
    "file_inclusion.common_payloads": "Payloads Comuns de Inclusão de Arquivo",
    "file_inclusion.path_traversal": "Path Traversal (LFI):",
    "file_inclusion.php_wrappers": "Wrappers PHP:",
    
    // Auth Bypass Module
    "auth_bypass.title": "Bypass de Autenticação",
    "auth_bypass.description": "Aprenda sobre técnicas de bypass de autenticação e vulnerabilidades",
    "auth_bypass.login_system": "Sistema de Login",
    "auth_bypass.login_desc": "Digite as credenciais para acessar o sistema",
    "auth_bypass.username": "Nome de Usuário",
    "auth_bypass.password": "Senha",
    "auth_bypass.login": "Entrar",
    "auth_bypass.logging_in": "Entrando...",
    "auth_bypass.auth_analysis": "Análise de Autenticação",
    "auth_bypass.attempted_credentials": "Credenciais Tentadas:",
    "auth_bypass.auth_result": "Resultado da Autenticação:",
    "auth_bypass.session_info": "Informações da Sessão:",
    "auth_bypass.security_analysis": "Análise de Segurança:",
    "auth_bypass.prevention_methods": "Métodos de Prevenção:",
    "auth_bypass.common_bypasses": "Técnicas Comuns de Bypass",
    "auth_bypass.sql_injection": "Injeção SQL:",
    "auth_bypass.logic_flaws": "Falhas Lógicas:",
    
    // Brute Force Module
    "brute_force.title": "Ataque de Força Bruta",
    "brute_force.description": "Aprenda sobre ataques de força bruta e mecanismos de proteção",
    "brute_force.attack_simulator": "Simulador de Ataque de Força Bruta",
    "brute_force.attack_desc": "Simule um ataque de força bruta contra um sistema de login",
    "brute_force.target_username": "Nome de Usuário Alvo",
    "brute_force.start_attack": "Iniciar Ataque de Força Bruta",
    "brute_force.attacking": "Atacando...",
    "brute_force.attack_progress": "Progresso do Ataque:",
    "brute_force.current_attempt": "Tentativa Atual:",
    "brute_force.attack_results": "Resultados do Ataque",
    "brute_force.total_attempts": "Total de Tentativas:",
    "brute_force.time_taken": "Tempo Gasto:",
    "brute_force.attack_status": "Status do Ataque:",
    "brute_force.found_password": "Senha Encontrada:",
    "brute_force.common_passwords": "Senhas Comuns para Testar:",
    
    // File Upload Module
    "file_upload.title": "Vulnerabilidade de Upload de Arquivo",
    "file_upload.description": "Aprenda sobre vulnerabilidades de upload de arquivo e técnicas de bypass",
    "file_upload.uploader": "Sistema de Upload de Arquivos",
    "file_upload.uploader_desc": "Faça upload de arquivos para o servidor (apenas imagens)",
    "file_upload.choose_file": "Escolher arquivo",
    "file_upload.upload": "Fazer Upload",
    "file_upload.uploading": "Enviando...",
    "file_upload.upload_results": "Resultados do Upload",
    "file_upload.filename": "Nome do Arquivo:",
    "file_upload.file_size": "Tamanho do Arquivo:",
    "file_upload.file_type": "Tipo do Arquivo:",
    "file_upload.upload_status": "Status do Upload:",
    "file_upload.upload_bypasses": "Bypasses de Upload de Arquivo",
    "file_upload.extension_bypass": "Bypass de Extensão:",
    "file_upload.mime_bypass": "Bypass de Tipo MIME:",
    "file_upload.double_extension": "Extensão Dupla:",
    
    // Insecure Captcha Module
    "insecure_captcha.title": "CAPTCHA Inseguro",
    "insecure_captcha.description": "Aprenda sobre técnicas de bypass de CAPTCHA e vulnerabilidades",
    "insecure_captcha.login_captcha": "Login com CAPTCHA",
    "insecure_captcha.login_desc": "Complete o CAPTCHA para prosseguir com o login",
    "insecure_captcha.captcha_code": "Código CAPTCHA",
    "insecure_captcha.enter_captcha": "Digite o código CAPTCHA mostrado acima",
    "insecure_captcha.refresh_captcha": "Atualizar CAPTCHA",
    "insecure_captcha.submit": "Enviar",
    "insecure_captcha.verifying": "Verificando...",
    "insecure_captcha.captcha_results": "Resultados da Verificação do CAPTCHA",
    "insecure_captcha.captcha_value": "Valor do CAPTCHA:",
    "insecure_captcha.user_input": "Entrada do Usuário:",
    "insecure_captcha.verification_result": "Resultado da Verificação:",
    "insecure_captcha.bypass_techniques": "Técnicas de Bypass de CAPTCHA",
    "insecure_captcha.client_side": "Validação Client-side:",
    "insecure_captcha.predictable": "Valores Previsíveis:",
    "insecure_captcha.reuse": "Reutilização de Sessão:",
    
    // Weak Session Module
    "weak_session.title": "IDs de Sessão Fracos",
    "weak_session.description": "Aprenda sobre vulnerabilidades de gerenciamento de sessão e ataques",
    "weak_session.session_manager": "Gerenciador de Sessão",
    "weak_session.session_desc": "Gere e analise IDs de sessão",
    "weak_session.generate_session": "Gerar ID de Sessão",
    "weak_session.generating": "Gerando...",
    "weak_session.session_analysis": "Análise do ID de Sessão",
    "weak_session.generated_id": "ID de Sessão Gerado:",
    "weak_session.entropy": "Nível de Entropia:",
    "weak_session.predictability": "Previsibilidade:",
    "weak_session.session_attacks": "Padrões de Ataque ao ID de Sessão",
    "weak_session.sequential": "IDs Sequenciais:",
    "weak_session.timestamp": "Baseado em Timestamp:",
    "weak_session.brute_force": "Força Bruta:",
    
    // OWASP Top 10 Module
    "owasp_top10.title": "OWASP Top 10",
    "owasp_top10.description": "Aprenda sobre as 10 principais vulnerabilidades de segurança em aplicações web",
    "owasp_top10.current_year": "OWASP Top 10 - 2023",
    "owasp_top10.vulnerability_list": "Lista de Vulnerabilidades",
    "owasp_top10.details": "Detalhes da Vulnerabilidade",
    "owasp_top10.examples": "Exemplos Práticos",
    "owasp_top10.mitigation": "Estratégias de Mitigação",
    
    // Secure Coding Module
    "secure_coding.title": "Codificação Segura",
    "secure_coding.description": "Aprenda práticas de desenvolvimento seguro e prevenção de vulnerabilidades",
    "secure_coding.best_practices": "Melhores Práticas",
    "secure_coding.code_review": "Revisão de Código",
    "secure_coding.static_analysis": "Análise Estática",
    "secure_coding.dynamic_testing": "Testes Dinâmicos",
    "secure_coding.secure_patterns": "Padrões Seguros",
    
    // Threat Modeling Module
    "threat_modeling.title": "Modelagem de Ameaças",
    "threat_modeling.description": "Aprenda a identificar e mitigar ameaças de segurança sistematicamente",
    "threat_modeling.methodology": "Metodologia STRIDE",
    "threat_modeling.threat_identification": "Identificação de Ameaças",
    "threat_modeling.risk_assessment": "Avaliação de Riscos",
    "threat_modeling.mitigation_strategies": "Estratégias de Mitigação",
    
    // Injection Attacks Module
    "injection_attacks.title": "Ataques de Injeção",
    "injection_attacks.description": "Aprenda sobre diferentes tipos de ataques de injeção e suas defesas",
    "injection_attacks.sql_injection": "Injeção SQL",
    "injection_attacks.command_injection": "Injeção de Comando",
    "injection_attacks.ldap_injection": "Injeção LDAP",
    "injection_attacks.xpath_injection": "Injeção XPath",
    "injection_attacks.prevention": "Técnicas de Prevenção",
    
    // Authentication Module
    "authentication.title": "Autenticação",
    "authentication.description": "Aprenda sobre sistemas de autenticação seguros e suas implementações",
    "authentication.multi_factor": "Autenticação Multi-Fator",
    "authentication.password_policies": "Políticas de Senha",
    "authentication.biometric_auth": "Autenticação Biométrica",
    "authentication.oauth_saml": "OAuth e SAML",
    "authentication.best_practices": "Melhores Práticas",
    
    // Session Management Module
    "session_management.title": "Gerenciamento de Sessão",
    "session_management.description": "Aprenda sobre gerenciamento seguro de sessões de usuário",
    "session_management.session_lifecycle": "Ciclo de Vida da Sessão",
    "session_management.token_management": "Gerenciamento de Tokens",
    "session_management.session_security": "Segurança de Sessão",
    "session_management.session_attacks": "Ataques a Sessão",
    
    // Network Protocols Module
    "network_protocols.title": "Protocolos de Rede",
    "network_protocols.description": "Aprenda sobre segurança em protocolos de rede",
    "network_protocols.tcp_ip": "TCP/IP Security",
    "network_protocols.tls_ssl": "TLS/SSL",
    "network_protocols.dns_security": "Segurança DNS",
    "network_protocols.vpn": "VPN e Túneis",
    
    // Firewalls Module
    "firewalls.title": "Firewalls",
    "firewalls.description": "Aprenda sobre configuração e gerenciamento de firewalls",
    "firewalls.packet_filtering": "Filtragem de Pacotes",
    "firewalls.stateful_inspection": "Inspeção Stateful",
    "firewalls.application_layer": "Firewall de Camada de Aplicação",
    "firewalls.rule_configuration": "Configuração de Regras",
    
    // Encryption Module
    "encryption.title": "Criptografia",
    "encryption.description": "Aprenda sobre criptografia e técnicas de proteção de dados",
    "encryption.symmetric_crypto": "Criptografia Simétrica",
    "encryption.asymmetric_crypto": "Criptografia Assimétrica",
    "encryption.hashing": "Funções Hash",
    "encryption.digital_signatures": "Assinaturas Digitais",
    "encryption.key_management": "Gerenciamento de Chaves",
    
    // Linux Security Module
    "linux_security.title": "Segurança Linux",
    "linux_security.description": "Aprenda sobre segurança em sistemas Linux",
    "linux_security.user_management": "Gerenciamento de Usuários",
    "linux_security.file_permissions": "Permissões de Arquivo",
    "linux_security.selinux": "SELinux",
    "linux_security.system_hardening": "Hardening do Sistema",
    "linux_security.log_monitoring": "Monitoramento de Logs",
    
    // Windows Security Module
    "windows_security.title": "Segurança Windows",
    "windows_security.description": "Aprenda sobre segurança em sistemas Windows",
    "windows_security.active_directory": "Active Directory",
    "windows_security.group_policy": "Group Policy",
    "windows_security.windows_defender": "Windows Defender",
    "windows_security.powershell_security": "Segurança PowerShell",
    
    // macOS Security Module
    "macos_security.title": "Segurança macOS",
    "macos_security.description": "Aprenda sobre segurança em sistemas macOS",
    "macos_security.gatekeeper": "Gatekeeper",
    "macos_security.system_integrity": "System Integrity Protection",
    "macos_security.keychain": "Keychain",
    "macos_security.xprotect": "XProtect",
    
    // Container Security Module
    "container_security.title": "Segurança de Contêineres",
    "container_security.description": "Aprenda sobre segurança em ambientes containerizados",
    "container_security.docker_security": "Segurança Docker",
    "container_security.kubernetes_security": "Segurança Kubernetes",
    "container_security.image_scanning": "Escaneamento de Imagens",
    "container_security.runtime_security": "Segurança em Runtime",
    
    // Python Security Module
    "python_security.title": "Segurança Python",
    "python_security.description": "Aprenda sobre práticas de segurança em desenvolvimento Python",
    "python_security.secure_coding": "Codificação Segura",
    "python_security.dependency_management": "Gerenciamento de Dependências",
    "python_security.web_framework_security": "Segurança em Frameworks Web",
    "python_security.serialization": "Segurança na Serialização",
    
    // JavaScript Security Module
    "javascript_security.title": "Segurança JavaScript",
    "javascript_security.description": "Aprenda sobre segurança em desenvolvimento JavaScript",
    "javascript_security.client_side": "Segurança Client-side",
    "javascript_security.nodejs_security": "Segurança Node.js",
    "javascript_security.package_security": "Segurança de Pacotes",
    "javascript_security.prototype_pollution": "Prototype Pollution",
    
    // C/C++ Security Module
    "c_cpp_security.title": "Segurança C/C++",
    "c_cpp_security.description": "Aprenda sobre segurança em desenvolvimento C/C++",
    "c_cpp_security.memory_management": "Gerenciamento de Memória",
    "c_cpp_security.buffer_overflow": "Buffer Overflow",
    "c_cpp_security.static_analysis": "Análise Estática",
    "c_cpp_security.secure_functions": "Funções Seguras",
    
    // Java Security Module
    "java_security.title": "Segurança Java",
    "java_security.description": "Aprenda sobre segurança em desenvolvimento Java",
    "java_security.jvm_security": "Segurança JVM",
    "java_security.serialization_attacks": "Ataques de Serialização",
    "java_security.spring_security": "Spring Security",
    "java_security.secure_coding": "Codificação Segura",
    
    // Assembly Security Module
    "assembly_security.title": "Segurança Assembly",
    "assembly_security.description": "Aprenda sobre segurança em programação Assembly e análise de baixo nível",
    "assembly_security.reverse_engineering": "Engenharia Reversa",
    "assembly_security.exploit_development": "Desenvolvimento de Exploits",
    "assembly_security.binary_analysis": "Análise Binária",
    "assembly_security.shellcode": "Shellcode",
    
    // Chat Bot Messages
    "chat.greeting_morning": "Bom dia",
    "chat.greeting_afternoon": "Boa tarde", 
    "chat.greeting_evening": "Boa noite",
    "chat.assistant_intro": "Eu sou seu Assistente de Segurança CyberLab. 🛡️",
    "chat.working_on_challenge": "Vejo que você está trabalhando no desafio {module}.",
    "chat.difficulty_level": "Este é um desafio de nível {difficulty}.",
    "chat.can_help_with": "Posso ajudá-lo com:",
    "chat.help_topics": "• Técnicas de exploração de vulnerabilidades\n• Sugestões de payloads e exemplos\n• Solução de erros comuns\n• Melhores práticas de segurança",
    "chat.what_explore": "O que você gostaria de explorar hoje?",
    "chat.based_on_module": "Com base no seu módulo atual, você pode tentar:",
    "chat.sql_injection_help": "Aqui estão alguns payloads de SQL injection para testar:",
    "chat.sql_remember": "Lembre-se de codificar caracteres especiais ao testar no navegador. Comece com a condição OR básica e avance para ataques UNION mais complexos.",
    "chat.xss_help": "Aqui estão alguns payloads XSS para testar:",
    "chat.xss_try_contexts": "Teste-os em diferentes contextos - parâmetros de URL, campos de formulário e cabeçalhos. Se um não funcionar, tente os outros!",
    "chat.command_injection_help": "Aqui estão payloads de command injection:",
    "chat.command_start_simple": "Comece com comandos simples como `whoami` ou `ls` para verificar se a injeção funciona, depois tente comandos mais complexos.",
    "chat.troubleshoot_help": "Posso ajudá-lo a solucionar problemas! Aqui estão alguns problemas comuns e soluções:",
    "chat.common_issues": "• **Erro de Sintaxe SQL**: Verifique o posicionamento das aspas e sintaxe de comentários\n• **Script Não Executando**: Tente diferentes contextos XSS ou contorne CSP\n• **Comando Não Encontrado**: Verifique se o comando existe no sistema alvo\n• **Acesso Negado**: Você pode precisar de privilégios diferentes ou caminhos de arquivo",
    "chat.share_error": "Você pode compartilhar a mensagem de erro específica que está vendo?",
    "chat.contextual_suggestions": "Com base no seu desafio atual, aqui estão algumas sugestões:",
    "chat.want_payloads": "Gostaria de payloads específicos para alguma dessas técnicas?",
    "chat.found_info": "Encontrei informações sobre **{name}**:",
    "chat.try_payloads": "Aqui estão alguns payloads para testar:",
    "chat.found_challenge": "Encontrei o desafio **{name}**. Aqui estão algumas dicas:",
    "chat.default_help": "Estou aqui para ajudar com seus desafios de cibersegurança! Você pode me perguntar sobre:\n\n• Vulnerabilidades específicas (SQL injection, XSS, etc.)\n• Exemplos de payloads e técnicas\n• Solução de erros\n• Melhores práticas de segurança",
    "chat.payloads_copied": "✅ Payloads copiados para a área de transferência!",
    "chat.copy_failed": "❌ Falha ao copiar payloads. Por favor, copie-os manualmente.",
    "chat.thinking": "Pensando...",
    "chat.online_ready": "Online • Pronto para ajudar",
    "chat.clear_history": "Limpar histórico do chat",
    "chat.copy_message": "Copiar mensagem",
    "chat.mark_helpful": "Marcar como útil",
    "chat.mark_not_helpful": "Marcar como não útil",
    "chat.export_payloads": "Exportar Payloads",
    "chat.ask_placeholder": "Pergunte sobre vulnerabilidades, payloads ou técnicas...",
    "chat.send_instruction": "Pressione Enter para enviar • Shift+Enter para nova linha",
    "chat.security_assistant": "Assistente de Segurança",
  },
  "es-ES": {
    "header.subtitle": "Plataforma Interactiva de Aprendizaje de Seguridad Web",
    "header.light": "Claro",
    "header.dark": "Oscuro",
    "sidebar.difficulty": "Nivel de Seguridad",
    "sidebar.modules": "Módulos de Aprendizaje",
    "sidebar.status": "Estado de la Sesión",
    "sidebar.current": "Módulo",
    "sidebar.level": "Nivel",
    "difficulty.easy": "Fácil",
    "difficulty.low": "Bajo",
    "difficulty.medium": "Medio",
    "difficulty.hard": "Difícil",
    "difficulty.high": "Alto",
    "difficulty.impossible": "Imposible",
    "security.low": "Bajo",
    "security.medium": "Medio",
    "security.high": "Alto",
    "security.level": "Nivel de Seguridad",
    "modules.home": "Inicio",
    "modules.sql-injection": "Inyección SQL",
    "modules.sql-blind": "Inyección SQL (Blind)",
    "modules.xss": "Cross-Site Scripting",
    "modules.command-injection": "Inyección de Comando",
    "modules.csrf": "Protección CSRF",
    "modules.file-inclusion": "Inclusión de Archivo",
    "modules.auth-bypass": "Bypass de Autenticación",
    "modules.brute-force": "Fuerza Bruta",
    "modules.file-upload": "Subida de Archivo",
    "modules.insecure-captcha": "CAPTCHA Inseguro",
    "modules.weak-session": "IDs de Sesión Débiles",
    "modules.coming_soon": "Módulo próximamente...",
    "modules.learn": "Aprender",
    "learn.mode": "Modo Aprendizaje",
    "learn.guided": "Aprendizaje Guiado",
    "learn.fundamentals": "Fundamentos de Seguridad",
    "learn.web_security": "Seguridad Web",
    "learn.network_security": "Seguridad de Red",
    "learn.os_security": "Seguridad de Sistemas Operativos",
    "learn.programming_security": "Programación Segura",
    "home.title": "Bienvenido a CyberLab ",
    "home.subtitle": "Plataforma Interactiva de Aprendizaje de Seguridad Web",
    "home.description": "CyberLab es una plataforma educativa interactiva diseñada para enseñar y entrenar seguridad web en un entorno controlado y seguro. El objetivo de esta plataforma es empoderar a estudiantes, desarrolladores y profesionales de seguridad para aprender, explorar y comprender vulnerabilidades comunes de aplicaciones web a través de la práctica práctica.",
    "home.get_started": "Comenzar",
    "home.general_instructions": "Instrucciones Generales",
    "home.general_instructions_content": "Los usuarios pueden explorar los módulos en cualquier orden, dependiendo de su nivel de conocimiento. Cada módulo incluye teoría, ejemplos prácticos y desafíos interactivos, permitiendo a los usuarios validar sus intentos de explotación. El sistema también contiene escenarios ocultos y no documentados para fomentar la curiosidad y promover enfoques de pentesting más creativos. Un modo de aprendizaje está disponible con pistas, tutoriales y referencias adicionales.",
    "home.warning": "¡ADVERTENCIA!",
    "home.warning_content": "CyberLab es una plataforma deliberadamente vulnerable, creada exclusivamente para fines educativos. NO debe ser desplegada en servidores de producción o expuesta a internet público, ya que esto puede comprometer la seguridad del entorno. Se recomienda encarecidamente ejecutar CyberLab en máquinas virtuales aisladas u otros entornos de laboratorio controlados.",
    "home.disclaimer": "Descargo de Responsabilidad",
    "home.disclaimer_content": "Los desarrolladores de CyberLab no asumen responsabilidad por cualquier mal uso de la plataforma. Este sistema debe ser usado solo para fines de aprendizaje y de acuerdo con prácticas éticas y legales.",
    "home.features.interactive": "Aprendizaje Interactivo",
    "home.features.interactive_desc": "Practica con vulnerabilidades reales",
    "home.features.multilingual": "Soporte Multilingüe",
    "home.features.multilingual_desc": "Disponible en múltiples idiomas",
    "home.features.difficulty": "Dificultad Progresiva",
    "home.features.difficulty_desc": "Desde principiante hasta niveles expertos",
    "sql.title": "Inyección SQL",
    "sql.description": "Aprende cómo funcionan las vulnerabilidades de inyección SQL y cómo explotarlas de forma segura.",
    "sql.user_id": "ID de Usuario",
    "sql.submit": "Consultar Base de Datos",
    "sql.results": "Resultados de la Consulta",
    "sql.placeholder": "Ingresa ID de usuario para buscar...",
    "xss.title": "Cross-Site Scripting (XSS)",
    "xss.description": "Comprende las vulnerabilidades XSS y practica explotándolas.",
    "xss.message": "Mensaje",
    "xss.submit": "Enviar Mensaje",
    "xss.results": "Visualización del Mensaje",
    "xss.placeholder": "Ingresa tu mensaje...",
    "command.search": "Buscar módulos...",
    "command.no_results": "No se encontraron resultados.",
    "command.navigation": "Navegación",
    "command.categories": "Categorías de Aprendizaje",
    "command.topics": "Tópicos de Aprendizaje",
    
    // Learn Mode
    "learn.category_not_found": "Categoría No Encontrada",
    "learn.category_not_found_desc": "La categoría de aprendizaje solicitada no existe.",
    "learn.progress": "Progreso",
    "learn.lessons": "lecciones",
    "learn.completed": "completadas",
    "learn.lesson_sections": "Secciones de la Lección",
    "learn.previous_section": "Sección Anterior",
    "learn.next_section": "Siguiente Sección",
    "learn.key_points": "Puntos Clave",
    "learn.code_examples": "Ejemplos de Código",
    "learn.vulnerable_code": "Código Vulnerable",
    "learn.secure_code": "Código Seguro",
    "learn.vulnerable_implementation": "Implementación Vulnerable",
    "learn.secure_implementation": "Implementación Segura",
    "learn.why_vulnerable": "Por qué es vulnerable:",
    "learn.why_secure": "Por qué es seguro:",
    "learn.prevention_strategies": "Estrategias de Prevención",
    "learn.theory": "Teoría",
    "learn.practical": "Práctico",
    "learn.security_fundamentals_desc": "Conceptos y principios esenciales de seguridad",
    "learn.web_security_desc": "Prácticas de seguridad en aplicaciones web",
    "learn.network_security_desc": "Protección de red y protocolos",
    "learn.understanding": "Entendiendo",
    "learn.secure_development": "Desarrollo Seguro",
    "learn.protection_and": "Protección y",
    
    // 404 Page
    "notfound.title": "Página No Encontrada",
    "notfound.description": "La página que buscas no existe o ha sido movida.",
    "notfound.return_home": "Volver al Inicio",
    
    // SQL Blind Module
    "sql_blind.title": "SQL Injection (Blind)",
    "sql_blind.description": "Aprende sobre técnicas de inyección SQL blind y métodos de explotación.",
    "sql_blind.user_id": "ID de Usuario",
    "sql_blind.search_user": "Buscar Usuario",
    "sql_blind.querying": "Consultando...",
    "sql_blind.analysis_results": "Resultados del Análisis - Técnica:",
    "sql_blind.query": "Consulta:",
    "sql_blind.response": "Respuesta:",
    "sql_blind.response_time": "Tiempo de Respuesta:",
    "sql_blind.suspicious_delay": "¡Retraso sospechoso!",
    "sql_blind.analysis_notes": "Notas del Análisis",
    "sql_blind.prevention_measures": "Medidas de Prevención",
    "sql_blind.payloads_title": "🎯 Payloads de Blind SQL Injection:",
    "sql_blind.boolean_based": "Basado en Boolean:",
    "sql_blind.time_based_mysql": "Basado en tiempo (MySQL):",
    "sql_blind.time_based_sqlserver": "Basado en tiempo (SQL Server):",
    "sql_blind.data_extraction": "Extracción de datos:",
    
    // XSS Module  
    "xss.message_board": "Sistema de Tablero de Mensajes",
    "xss.processing": "Procesando...",
    "xss.message_preview": "Vista Previa del Mensaje:",
    "xss.security_analysis": "Análisis de Seguridad",
    "xss.original_input": "Entrada Original:",
    "xss.processed_output": "Salida Procesada:",
    "xss.educational_note": "Nota Educativa:",
    "xss.prevention": "Prevención:",
    "xss.payloads_title": "💡 Prueba Estos Payloads XSS:",
    "xss.basic_script": "Script básico:",
    "xss.image_onerror": "Image onerror:",
    "xss.javascript_url": "JavaScript URL:",
    "xss.event_handler": "Manejador de eventos:",
    "xss.svg_payload": "Payload SVG:",
    "xss.body_onload": "Body onload:",
    "xss.educational_purpose": "Solo Con Fines Educativos: Estos payloads son para aprendizaje. Nunca los uses en sistemas que no posees o sin permiso explícito.",
    
    // Command Injection Module
    "command_injection.title": "Command Injection",
    "command_injection.description": "Aprende sobre vulnerabilidades de inyección de comandos en aplicaciones web.",
    "command_injection.network_ping": "Utilidad de Ping de Red",
    "command_injection.host_ip": "Host/Dirección IP",
    "command_injection.host_placeholder": "Ingresa host o dirección IP para ping...",
    "command_injection.execute_ping": "Ejecutar Ping",
    "command_injection.executing": "Ejecutando...",
    "command_injection.command_results": "Resultados del Comando",
    "command_injection.executed_command": "Comando Ejecutado:",
    "command_injection.command_output": "Salida del Comando:",
    "command_injection.payloads_title": "💡 Prueba Estos Payloads:",
    "command_injection.command_chaining": "Encadenamiento de comandos:",
    "command_injection.logical_and": "AND lógico:",
    "command_injection.pipe_operator": "Operador pipe:",
    "command_injection.background_execution": "Ejecución en background:",
    
    // CSRF Module
    "csrf.title": "Protección CSRF", 
    "csrf.description": "Aprende sobre ataques Cross-Site Request Forgery y defensas.",
    "csrf.profile_update": "Formulario de Actualización de Perfil",
    "csrf.email_address": "Dirección de Email",
    "csrf.email_placeholder": "Ingresa tu dirección de email...",
    "csrf.new_password": "Nueva Contraseña",
    "csrf.password_placeholder": "Ingresa nueva contraseña...",
    "csrf.csrf_token": "Token CSRF:",
    "csrf.update_profile": "Actualizar Perfil",
    "csrf.updating": "Actualizando...",
    "csrf.form_analysis": "Análisis del Formulario",
    "csrf.generated_form": "HTML del Formulario Generado:",
    "csrf.csrf_attack": "Posible Ataque CSRF:",
    "csrf.security_analysis": "Análisis de Seguridad:",
    "csrf.protection_methods": "🛡️ Métodos de Protección CSRF:",
    "csrf.anti_csrf_tokens": "✓ Tokens Anti-CSRF",
    "csrf.anti_csrf_desc": "Incluye tokens únicos e impredecibles en formularios",
    "csrf.samesite_cookies": "✓ Cookies SameSite",
    "csrf.samesite_desc": "Previene que las cookies sean enviadas en peticiones cross-site", 
    "csrf.referrer_validation": "✓ Validación de Referrer",
    "csrf.referrer_desc": "Verifica que las peticiones vengan de orígenes esperados",
    "csrf.double_submit": "✓ Patrón Double Submit",
    "csrf.double_submit_desc": "Envía token tanto en cookie como en campo del formulario",
    
    // SQL Injection Module
    "sql_injection.title": "Inyección SQL",
    "sql_injection.description": "Aprende cómo funcionan las vulnerabilidades de inyección SQL y cómo explotarlas de forma segura.",
    "sql_injection.user_lookup": "Sistema de Búsqueda de Usuario", 
    "sql_injection.querying": "Consultando...",
    "sql_injection.executed_query": "Consulta Ejecutada:",
    "sql_injection.retrieved_data": "Datos Recuperados:",
    "sql_injection.no_results": "No se encontraron resultados para la entrada proporcionada.",
    "sql_injection.educational_note": "Nota Educativa:",
    "sql_injection.prevention": "Prevención:",
    "sql_injection.payloads_title": "💡 Prueba Estos Payloads:",
    "sql_injection.basic_bypass": "Bypass básico:",
    "sql_injection.comment_injection": "Inyección de comentario:",
    "sql_injection.union_attack": "Ataque UNION:",
    "sql_injection.boolean_based": "Basado en Boolean:",
    
    // File Inclusion Module
    "file_inclusion.title": "Inclusión de Archivo",
    "file_inclusion.description": "Aprende sobre vulnerabilidades de Inclusión Local y Remota de Archivos",
    "file_inclusion.file_viewer": "Aplicación Visualizadora de Archivos",
    "file_inclusion.file_viewer_desc": "Ingresa un nombre de archivo para incluir y mostrar su contenido",
    "file_inclusion.file_to_include": "Archivo a incluir:",
    "file_inclusion.file_placeholder": "Ingresa el nombre del archivo (ej: home.php, ../../../etc/passwd)",
    "file_inclusion.include_file": "Incluir Archivo",
    "file_inclusion.loading": "Cargando...",
    "file_inclusion.analysis": "Análisis de Inclusión de Archivo",
    "file_inclusion.requested_file": "Archivo Solicitado:",
    "file_inclusion.file_contents": "Contenido del Archivo:",
    "file_inclusion.security_analysis": "Análisis de Seguridad:",
    "file_inclusion.prevention_methods": "Métodos de Prevención:",
    "file_inclusion.common_payloads": "Payloads Comunes de Inclusión de Archivo",
    "file_inclusion.path_traversal": "Path Traversal (LFI):",
    "file_inclusion.php_wrappers": "Wrappers PHP:",
    
    // Auth Bypass Module
    "auth_bypass.title": "Bypass de Autenticación",
    "auth_bypass.description": "Aprende sobre técnicas de bypass de autenticación y vulnerabilidades",
    "auth_bypass.login_system": "Sistema de Login",
    "auth_bypass.login_desc": "Ingresa las credenciales para acceder al sistema",
    "auth_bypass.username": "Nombre de Usuario",
    "auth_bypass.password": "Contraseña",
    "auth_bypass.login": "Iniciar Sesión",
    "auth_bypass.logging_in": "Iniciando sesión...",
    "auth_bypass.auth_analysis": "Análisis de Autenticación",
    "auth_bypass.attempted_credentials": "Credenciales Intentadas:",
    "auth_bypass.auth_result": "Resultado de la Autenticación:",
    "auth_bypass.session_info": "Información de la Sesión:",
    "auth_bypass.security_analysis": "Análisis de Seguridad:",
    "auth_bypass.prevention_methods": "Métodos de Prevención:",
    "auth_bypass.common_bypasses": "Técnicas Comunes de Bypass",
    "auth_bypass.sql_injection": "Inyección SQL:",
    "auth_bypass.logic_flaws": "Fallas Lógicas:",
    
    // Brute Force Module
    "brute_force.title": "Ataque de Fuerza Bruta",
    "brute_force.description": "Aprende sobre ataques de fuerza bruta y mecanismos de protección",
    "brute_force.attack_simulator": "Simulador de Ataque de Fuerza Bruta",
    "brute_force.attack_desc": "Simula un ataque de fuerza bruta contra un sistema de login",
    "brute_force.target_username": "Nombre de Usuario Objetivo",
    "brute_force.start_attack": "Iniciar Ataque de Fuerza Bruta",
    "brute_force.attacking": "Atacando...",
    "brute_force.attack_progress": "Progreso del Ataque:",
    "brute_force.current_attempt": "Intento Actual:",
    "brute_force.attack_results": "Resultados del Ataque",
    "brute_force.total_attempts": "Total de Intentos:",
    "brute_force.time_taken": "Tiempo Transcurrido:",
    "brute_force.attack_status": "Estado del Ataque:",
    "brute_force.found_password": "Contraseña Encontrada:",
    "brute_force.common_passwords": "Contraseñas Comunes para Probar:",
    
    // File Upload Module
    "file_upload.title": "Vulnerabilidad de Subida de Archivo",
    "file_upload.description": "Aprende sobre vulnerabilidades de subida de archivos y técnicas de bypass",
    "file_upload.uploader": "Sistema de Subida de Archivos",
    "file_upload.uploader_desc": "Sube archivos al servidor (solo imágenes)",
    "file_upload.choose_file": "Elegir archivo",
    "file_upload.upload": "Subir Archivo",
    "file_upload.uploading": "Subiendo...",
    "file_upload.upload_results": "Resultados de la Subida",
    "file_upload.filename": "Nombre del Archivo:",
    "file_upload.file_size": "Tamaño del Archivo:",
    "file_upload.file_type": "Tipo del Archivo:",
    "file_upload.upload_status": "Estado de la Subida:",
    "file_upload.upload_bypasses": "Bypasses de Subida de Archivo",
    "file_upload.extension_bypass": "Bypass de Extensión:",
    "file_upload.mime_bypass": "Bypass de Tipo MIME:",
    "file_upload.double_extension": "Extensión Doble:",
    
    // Insecure Captcha Module
    "insecure_captcha.title": "CAPTCHA Inseguro",
    "insecure_captcha.description": "Aprende sobre técnicas de bypass de CAPTCHA y vulnerabilidades",
    "insecure_captcha.login_captcha": "Login con CAPTCHA",
    "insecure_captcha.login_desc": "Completa el CAPTCHA para proceder con el login",
    "insecure_captcha.captcha_code": "Código CAPTCHA",
    "insecure_captcha.enter_captcha": "Ingresa el código CAPTCHA mostrado arriba",
    "insecure_captcha.refresh_captcha": "Actualizar CAPTCHA",
    "insecure_captcha.submit": "Enviar",
    "insecure_captcha.verifying": "Verificando...",
    "insecure_captcha.captcha_results": "Resultados de la Verificación del CAPTCHA",
    "insecure_captcha.captcha_value": "Valor del CAPTCHA:",
    "insecure_captcha.user_input": "Entrada del Usuario:",
    "insecure_captcha.verification_result": "Resultado de la Verificación:",
    "insecure_captcha.bypass_techniques": "Técnicas de Bypass de CAPTCHA",
    "insecure_captcha.client_side": "Validación del Lado del Cliente:",
    "insecure_captcha.predictable": "Valores Predecibles:",
    "insecure_captcha.reuse": "Reutilización de Sesión:",
    
    // Weak Session Module
    "weak_session.title": "IDs de Sesión Débiles",
    "weak_session.description": "Aprende sobre vulnerabilidades de gestión de sesión y ataques",
    "weak_session.session_manager": "Gestor de Sesión",
    "weak_session.session_desc": "Genera y analiza IDs de sesión",
    "weak_session.generate_session": "Generar ID de Sesión",
    "weak_session.generating": "Generando...",
    "weak_session.session_analysis": "Análisis del ID de Sesión",
    "weak_session.generated_id": "ID de Sesión Generado:",
    "weak_session.entropy": "Nivel de Entropía:",
    "weak_session.predictability": "Predictibilidad:",
    "weak_session.session_attacks": "Patrones de Ataque al ID de Sesión",
    "weak_session.sequential": "IDs Secuenciales:",
    "weak_session.timestamp": "Basado en Timestamp:",
    "weak_session.brute_force": "Fuerza Bruta:",
    
    // OWASP Top 10 Module
    "owasp_top10.title": "OWASP Top 10",
    "owasp_top10.description": "Aprende sobre las 10 principales vulnerabilidades de seguridad en aplicaciones web",
    "owasp_top10.current_year": "OWASP Top 10 - 2023",
    "owasp_top10.vulnerability_list": "Lista de Vulnerabilidades",
    "owasp_top10.details": "Detalles de la Vulnerabilidad",
    "owasp_top10.examples": "Ejemplos Prácticos",
    "owasp_top10.mitigation": "Estrategias de Mitigación",
    
    // Secure Coding Module
    "secure_coding.title": "Codificación Segura",
    "secure_coding.description": "Aprende prácticas de desarrollo seguro y prevención de vulnerabilidades",
    "secure_coding.best_practices": "Mejores Prácticas",
    "secure_coding.code_review": "Revisión de Código",
    "secure_coding.static_analysis": "Análisis Estático",
    "secure_coding.dynamic_testing": "Pruebas Dinámicas",
    "secure_coding.secure_patterns": "Patrones Seguros",
    
    // Threat Modeling Module
    "threat_modeling.title": "Modelado de Amenazas",
    "threat_modeling.description": "Aprende a identificar y mitigar amenazas de seguridad sistemáticamente",
    "threat_modeling.methodology": "Metodología STRIDE",
    "threat_modeling.threat_identification": "Identificación de Amenazas",
    "threat_modeling.risk_assessment": "Evaluación de Riesgos",
    "threat_modeling.mitigation_strategies": "Estrategias de Mitigación",
    
    // Injection Attacks Module
    "injection_attacks.title": "Ataques de Inyección",
    "injection_attacks.description": "Aprende sobre diferentes tipos de ataques de inyección y sus defensas",
    "injection_attacks.sql_injection": "Inyección SQL",
    "injection_attacks.command_injection": "Inyección de Comando",
    "injection_attacks.ldap_injection": "Inyección LDAP",
    "injection_attacks.xpath_injection": "Inyección XPath",
    "injection_attacks.prevention": "Técnicas de Prevención",
    
    // Authentication Module
    "authentication.title": "Autenticación",
    "authentication.description": "Aprende sobre sistemas de autenticación seguros y sus implementaciones",
    "authentication.multi_factor": "Autenticación Multi-Factor",
    "authentication.password_policies": "Políticas de Contraseña",
    "authentication.biometric_auth": "Autenticación Biométrica",
    "authentication.oauth_saml": "OAuth y SAML",
    "authentication.best_practices": "Mejores Prácticas",
    
    // Session Management Module
    "session_management.title": "Gestión de Sesión",
    "session_management.description": "Aprende sobre gestión segura de sesiones de usuario",
    "session_management.session_lifecycle": "Ciclo de Vida de la Sesión",
    "session_management.token_management": "Gestión de Tokens",
    "session_management.session_security": "Seguridad de Sesión",
    "session_management.session_attacks": "Ataques a la Sesión",
    
    // Network Protocols Module
    "network_protocols.title": "Protocolos de Red",
    "network_protocols.description": "Aprende sobre seguridad en protocolos de red",
    "network_protocols.tcp_ip": "TCP/IP Security",
    "network_protocols.tls_ssl": "TLS/SSL",
    "network_protocols.dns_security": "Seguridad DNS",
    "network_protocols.vpn": "VPN y Túneles",
    
    // Firewalls Module
    "firewalls.title": "Firewalls",
    "firewalls.description": "Aprende sobre configuración y gestión de firewalls",
    "firewalls.packet_filtering": "Filtrado de Paquetes",
    "firewalls.stateful_inspection": "Inspección Stateful",
    "firewalls.application_layer": "Firewall de Capa de Aplicación",
    "firewalls.rule_configuration": "Configuración de Reglas",
    
    // Encryption Module
    "encryption.title": "Criptografía",
    "encryption.description": "Aprende sobre criptografía y técnicas de protección de datos",
    "encryption.symmetric_crypto": "Criptografía Simétrica",
    "encryption.asymmetric_crypto": "Criptografía Asimétrica",
    "encryption.hashing": "Funciones Hash",
    "encryption.digital_signatures": "Firmas Digitales",
    "encryption.key_management": "Gestión de Claves",
    
    // Linux Security Module
    "linux_security.title": "Seguridad Linux",
    "linux_security.description": "Aprende sobre seguridad en sistemas Linux",
    "linux_security.user_management": "Gestión de Usuarios",
    "linux_security.file_permissions": "Permisos de Archivo",
    "linux_security.selinux": "SELinux",
    "linux_security.system_hardening": "Hardening del Sistema",
    "linux_security.log_monitoring": "Monitoreo de Logs",
    
    // Windows Security Module
    "windows_security.title": "Seguridad Windows",
    "windows_security.description": "Aprende sobre seguridad en sistemas Windows",
    "windows_security.active_directory": "Active Directory",
    "windows_security.group_policy": "Group Policy",
    "windows_security.windows_defender": "Windows Defender",
    "windows_security.powershell_security": "Seguridad PowerShell",
    
    // macOS Security Module
    "macos_security.title": "Seguridad macOS",
    "macos_security.description": "Aprende sobre seguridad en sistemas macOS",
    "macos_security.gatekeeper": "Gatekeeper",
    "macos_security.system_integrity": "System Integrity Protection",
    "macos_security.keychain": "Keychain",
    "macos_security.xprotect": "XProtect",
    
    // Container Security Module
    "container_security.title": "Seguridad de Contenedores",
    "container_security.description": "Aprende sobre seguridad en ambientes containerizados",
    "container_security.docker_security": "Seguridad Docker",
    "container_security.kubernetes_security": "Seguridad Kubernetes",
    "container_security.image_scanning": "Escaneo de Imágenes",
    "container_security.runtime_security": "Seguridad en Runtime",
    
    // Python Security Module
    "python_security.title": "Seguridad Python",
    "python_security.description": "Aprende sobre prácticas de seguridad en desarrollo Python",
    "python_security.secure_coding": "Codificación Segura",
    "python_security.dependency_management": "Gestión de Dependencias",
    "python_security.web_framework_security": "Seguridad en Frameworks Web",
    "python_security.serialization": "Seguridad en la Serialización",
    
    // JavaScript Security Module
    "javascript_security.title": "Seguridad JavaScript",
    "javascript_security.description": "Aprende sobre seguridad en desarrollo JavaScript",
    "javascript_security.client_side": "Seguridad Client-side",
    "javascript_security.nodejs_security": "Seguridad Node.js",
    "javascript_security.package_security": "Seguridad de Paquetes",
    "javascript_security.prototype_pollution": "Prototype Pollution",
    
    // C/C++ Security Module
    "c_cpp_security.title": "Seguridad C/C++",
    "c_cpp_security.description": "Aprende sobre seguridad en desarrollo C/C++",
    "c_cpp_security.memory_management": "Gestión de Memoria",
    "c_cpp_security.buffer_overflow": "Buffer Overflow",
    "c_cpp_security.static_analysis": "Análisis Estático",
    "c_cpp_security.secure_functions": "Funciones Seguras",
    
    // Java Security Module
    "java_security.title": "Seguridad Java",
    "java_security.description": "Aprende sobre seguridad en desarrollo Java",
    "java_security.jvm_security": "Seguridad JVM",
    "java_security.serialization_attacks": "Ataques de Serialización",
    "java_security.spring_security": "Spring Security",
    "java_security.secure_coding": "Codificación Segura",
    
    // Assembly Security Module
    "assembly_security.title": "Seguridad Assembly",
    "assembly_security.description": "Aprende sobre seguridad en programación Assembly y análisis de bajo nivel",
    "assembly_security.reverse_engineering": "Ingeniería Inversa",
    "assembly_security.exploit_development": "Desarrollo de Exploits",
    "assembly_security.binary_analysis": "Análisis Binario",
    "assembly_security.shellcode": "Shellcode",
    
    // Chat Bot Messages
    "chat.greeting_morning": "Buenos días",
    "chat.greeting_afternoon": "Buenas tardes", 
    "chat.greeting_evening": "Buenas noches",
    "chat.assistant_intro": "Soy tu Asistente de Seguridad CyberLab. 🛡️",
    "chat.working_on_challenge": "Veo que estás trabajando en el desafío {module}.",
    "chat.difficulty_level": "Este es un desafío de nivel {difficulty}.",
    "chat.can_help_with": "Puedo ayudarte con:",
    "chat.help_topics": "• Técnicas de explotación de vulnerabilidades\n• Sugerencias de payloads y ejemplos\n• Solución de errores comunes\n• Mejores prácticas de seguridad",
    "chat.what_explore": "¿Qué te gustaría explorar hoy?",
    "chat.based_on_module": "Basado en tu módulo actual, podrías intentar:",
    "chat.sql_injection_help": "Aquí tienes algunos payloads de SQL injection para probar:",
    "chat.sql_remember": "Recuerda codificar caracteres especiales al probar en el navegador. Comienza con la condición OR básica y avanza hacia ataques UNION más complejos.",
    "chat.xss_help": "Aquí tienes algunos payloads XSS para probar:",
    "chat.xss_try_contexts": "Pruébalos en diferentes contextos - parámetros de URL, campos de formulario y headers. ¡Si uno no funciona, prueba los otros!",
    "chat.command_injection_help": "Aquí tienes payloads de command injection:",
    "chat.command_start_simple": "Comienza con comandos simples como `whoami` o `ls` para verificar que la inyección funciona, luego prueba comandos más complejos.",
    "chat.troubleshoot_help": "¡Puedo ayudarte a solucionar problemas! Aquí tienes algunos problemas comunes y soluciones:",
    "chat.common_issues": "• **Error de Sintaxis SQL**: Verifica la colocación de comillas y sintaxis de comentarios\n• **Script No Ejecutándose**: Prueba diferentes contextos XSS o evita CSP\n• **Comando No Encontrado**: Verifica que el comando existe en el sistema objetivo\n• **Acceso Denegado**: Puede que necesites diferentes privilegios o rutas de archivo",
    "chat.share_error": "¿Puedes compartir el mensaje de error específico que estás viendo?",
    "chat.contextual_suggestions": "Basado en tu desafío actual, aquí tienes algunas sugerencias:",
    "chat.want_payloads": "¿Te gustarían payloads específicos para alguna de estas técnicas?",
    "chat.found_info": "Encontré información sobre **{name}**:",
    "chat.try_payloads": "Aquí tienes algunos payloads para probar:",
    "chat.found_challenge": "Encontré el desafío **{name}**. Aquí tienes algunas pistas:",
    "chat.default_help": "¡Estoy aquí para ayudar con tus desafíos de ciberseguridad! Puedes preguntarme sobre:\n\n• Vulnerabilidades específicas (SQL injection, XSS, etc.)\n• Ejemplos de payloads y técnicas\n• Solución de errores\n• Mejores prácticas de seguridad",
    "chat.payloads_copied": "✅ ¡Payloads copiados al portapapeles!",
    "chat.copy_failed": "❌ Error al copiar payloads. Por favor, cópialos manualmente.",
    "chat.thinking": "Pensando...",
    "chat.online_ready": "En línea • Listo para ayudar",
    "chat.clear_history": "Limpiar historial del chat",
    "chat.copy_message": "Copiar mensaje",
    "chat.mark_helpful": "Marcar como útil",
    "chat.mark_not_helpful": "Marcar como no útil",
    "chat.export_payloads": "Exportar Payloads",
    "chat.ask_placeholder": "Pregunta sobre vulnerabilidades, payloads o técnicas...",
    "chat.send_instruction": "Presiona Enter para enviar • Shift+Enter para nueva línea",
    "chat.security_assistant": "Asistente de Seguridad",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>("en-US");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("cyberlab-language") as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("cyberlab-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguageContext = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguageContext must be used within a LanguageProvider");
  }
  return context;
};